env:
  es6: true
  browser: true
plugins:
  - 'react'
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
    legacyDecorators: true
settings:
  react:
    version: '16'
rules:
  'indent':
    - error
    - tab
    - SwitchCase: 1
  'linebreak-style':
    - error
    - unix
  'quotes':
    - error
    - single
  'semi':
    - error
    - always
  'no-console': off
  'no-empty': error
  'keyword-spacing':
    - error
  'no-mixed-spaces-and-tabs':
    - error
  'object-curly-spacing':
    - error
    - always
  'no-trailing-spaces':
    - error
  'react/jsx-curly-spacing':
    - error
    - when: 'never'
      spacing:
        objectLiterals: 'never'
  'react/prop-types': error
  'react/no-unused-prop-types': error
  'react/jsx-key': error
